doctrine:
    dbal:
        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Encounter:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infra/MatchMaker/Storage/ORM/Encounter'
                prefix: 'App\Domain\MatchMaker\Encounter'
            Player:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infra/MatchMaker/Storage/ORM/Player'
                prefix: 'App\Domain\MatchMaker\Player'
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infra/User/Storage/ORM'
                prefix: 'App\Infra\User\Storage\Entity'
